"use client";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { STRATEGIES } from "@/lib/analysis-types";
interface CurvePoint { date:string; equity:number; return_pct:number }
interface BacktestResult { strategy_id:string; name:string; metrics:Record<string,number|null>; equity_curve:CurvePoint[]; trades:Array<{symbol:string;entry_day:string;exit_day:string;quantity:number;pnl_cash:number;exit_reason:string}> }
interface BacktestReport { results:BacktestResult[]; warnings:string[]; calendar_days:number; excluded:Array<{symbol:string;reason:string}> }
interface Job {id:number;status:string;created_at:string;error:string|null}
const colors=["#2563eb","#9333ea","#d97706"];
function EquityChart({results}:{results:BacktestResult[]}) {
  const points=results.flatMap(result=>result.equity_curve.map(point=>point.return_pct));
  if(!points.length)return null;
  const low=Math.min(0,...points),high=Math.max(1,...points),span=high-low||1;
  const maxLength=Math.max(...results.map(result=>result.equity_curve.length));
  return <div className="rounded border p-3"><div className="mb-3 flex flex-wrap gap-4 text-sm">{results.map((result,index)=><span key={result.strategy_id} className="flex items-center gap-2"><span className="inline-block h-1 w-5" style={{backgroundColor:colors[index]}}/>{result.name}</span>)}</div><svg role="img" aria-label="三个策略的累计收益曲线，详细收益率见指标表" viewBox="0 0 900 300" className="w-full"><title>三策略累计收益率（%）</title>{[0,.25,.5,.75,1].map(fraction=><g key={fraction}><line x1="65" y1={20+fraction*230} x2="875" y2={20+fraction*230} stroke="currentColor" opacity=".12"/><text x="58" y={24+fraction*230} textAnchor="end" fontSize="11" fill="currentColor">{(high-fraction*span).toFixed(1)}%</text></g>)}{results.map((result,index)=><polyline key={result.strategy_id} fill="none" stroke={colors[index]} strokeWidth="2" points={result.equity_curve.map((point,i)=>`${65+i/Math.max(1,maxLength-1)*810},${250-(point.return_pct-low)/span*230}`).join(" ")}/>)}<text x="65" y="278" fontSize="11" fill="currentColor">{results[0]?.equity_curve[0]?.date}</text><text x="875" y="278" textAnchor="end" fontSize="11" fill="currentColor">{results[0]?.equity_curve.at(-1)?.date}</text></svg></div>;
}
export default function BacktestPage() {
  const [mode,setMode]=useState("stock"),[symbol,setSymbol]=useState("");
  const [start,setStart]=useState("2023-05-01"),[end,setEnd]=useState(()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Shanghai"}));
  const [cash,setCash]=useState("100000"),[positions,setPositions]=useState("4"),[size,setSize]=useState("25");
  const [available,setAvailable]=useState<boolean|null>(null),[jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState<number|null>(null);
  const [report,setReport]=useState<BacktestReport|null>(null),[progress,setProgress]=useState<{stage:string;processed:number;total:number}|null>(null),[error,setError]=useState("");
  const [starting,setStarting]=useState(false);
  const load=useCallback(async()=>{try{const response=await fetch("/api/backtests");const data=await response.json();if(!response.ok)throw new Error(data.error??"加载回测失败");setAvailable(data.available);setJobs(data.jobs.map((job:Job)=>({...job,id:Number(job.id)})));}catch(err){setError(String(err));}},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);const interval=setInterval(()=>void load(),5000);return()=>{clearTimeout(timer);clearInterval(interval);};},[load]);
  useEffect(()=>{if(!selected)return;const abort=new AbortController();const loadReport=async()=>{try{const response=await fetch(`/api/backtests/${selected}`,{signal:abort.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);setReport(data.report);setProgress(data.progress);setError(data.job.error??"");}catch(err){if(!abort.signal.aborted)setError(String(err));}};void loadReport();const timer=setInterval(()=>void loadReport(),5000);return()=>{abort.abort();clearInterval(timer);};},[selected]);
  const run=async()=>{setStarting(true);try{const response=await fetch("/api/backtests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:mode==="stock"?[symbol.trim()]:[],start,end,initial_cash:Number(cash),max_positions:Number(positions),position_size_pct:Number(size)/100,strategies:STRATEGIES.map(row=>row.id)})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSelected(data.jobId);setReport(null);toast.success("本地回测已进入任务队列");void load();}catch(err){toast.error(String(err));}finally{setStarting(false);}};
  const metricColumns=[{key:"annualized_return_pct",name:"年化收益率",percent:true},{key:"max_drawdown_pct",name:"最大回撤",percent:true},{key:"sharpe_ratio",name:"夏普比率"},{key:"payoff_ratio",name:"盈亏比"},{key:"win_rate_pct",name:"胜率",percent:true},{key:"closed_trades",name:"已平仓笔数"}];
  return <div className="space-y-5"><div><h1 className="text-xl font-semibold">策略回测</h1><p className="mt-1 text-sm text-muted-foreground">同一历史区间、相同资金约束，比较三套策略的表现。</p></div>{available===false&&<p className="rounded border bg-muted p-4 text-sm">请在本地研究环境运行回测。生产环境不执行回测任务。</p>}
    <Tabs value={mode} onValueChange={setMode}><TabsList variant="line"><TabsTrigger value="stock">个股回测</TabsTrigger><TabsTrigger value="market">全市场回测</TabsTrigger></TabsList><TabsContent value="stock"><div className="max-w-xs"><Label htmlFor="backtest-symbol">股票代码</Label><Input id="backtest-symbol" placeholder="600036.SH" value={symbol} onChange={event=>setSymbol(event.target.value)}/></div></TabsContent><TabsContent value="market"><p className="text-sm text-muted-foreground">使用本地历史行情覆盖的全市场股票；报告会列出数据缺失与样本范围限制。</p></TabsContent></Tabs>
    <form className="flex flex-wrap items-end gap-3 rounded border p-4" onSubmit={event=>{event.preventDefault();void run();}}>{[{id:"start",label:"开始日期",value:start,set:setStart,type:"date"},{id:"end",label:"结束日期",value:end,set:setEnd,type:"date"},{id:"cash",label:"初始资金（元）",value:cash,set:setCash,type:"number"},{id:"positions",label:"最大持仓数",value:positions,set:setPositions,type:"number"},{id:"size",label:"单笔仓位上限（%）",value:size,set:setSize,type:"number"}].map(field=><div key={field.id}><Label htmlFor={`bt-${field.id}`}>{field.label}</Label><Input className="w-40" id={`bt-${field.id}`} type={field.type} required value={field.value} onChange={event=>field.set(event.target.value)}/></div>)}<Button type="submit" disabled={!available||starting||(mode==="stock"&&!symbol.trim())}>{starting?"启动中…":"运行三策略回测"}</Button></form>
    <div className="flex flex-wrap items-center gap-3"><Label htmlFor="backtest-history">历史任务</Label><select id="backtest-history" className="h-9 min-w-72 rounded border bg-background px-2 text-sm" value={selected??""} onChange={event=>{setSelected(Number(event.target.value)||null);setReport(null);}}><option value="">选择回测任务</option>{jobs.map(job=><option key={job.id} value={job.id}>#{job.id} · {job.created_at} · {job.status==="success"?"已完成":job.status==="failed"?"失败":job.status==="running"?"运行中":"等待中"}</option>)}</select>{selected&&jobs.find(job=>job.id===selected)?.status==="failed"&&<Button variant="outline" onClick={async()=>{const response=await fetch(`/api/backtests/${selected}`,{method:"POST"});if(response.ok){toast.success("正在从检查点继续");void load();}else{const data=await response.json();toast.error(data.error??"重试失败");}}}>从检查点重试</Button>}{progress&&<span className="text-sm text-muted-foreground">{progress.stage} · {progress.processed}/{progress.total}</span>}</div>
    {error&&<p role="alert" className="rounded border border-destructive/30 p-3 text-sm text-destructive">{error}</p>}
    {report&&<><div className="overflow-x-auto rounded border"><table className="w-full min-w-[720px] text-sm"><thead className="bg-muted/40"><tr><th className="p-3 text-left">策略</th>{metricColumns.map(column=><th key={column.key} className="p-3 text-right">{column.name}</th>)}</tr></thead><tbody>{report.results.map(result=><tr key={result.strategy_id} className="border-t"><th className="p-3 text-left font-medium">{result.name}</th>{metricColumns.map(column=><td key={column.key} className="p-3 text-right tabular-nums">{result.metrics[column.key]==null?"N/A":`${result.metrics[column.key]!.toFixed(column.key==="closed_trades"?0:2)}${column.percent?"%":""}`}</td>)}</tr>)}</tbody></table></div><EquityChart results={report.results}/><p className="text-xs text-muted-foreground">覆盖 {report.calendar_days} 个交易日 · 盈亏比采用已平仓交易净金额 · 夏普无风险利率为 0 · 区间末未平仓持仓按市值计入权益</p><ul className="space-y-1 text-xs text-muted-foreground">{report.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul><details className="rounded border p-3"><summary className="cursor-pointer text-sm">成交明细与排除原因</summary><div className="mt-3 max-h-96 overflow-auto">{report.results.map(result=><div key={result.strategy_id}><h3 className="my-3 text-sm font-medium">{result.name}</h3><table className="w-full text-xs"><thead><tr>{["股票","买入日","卖出日","数量","净盈亏","退出原因"].map(name=><th className="p-2 text-left" key={name}>{name}</th>)}</tr></thead><tbody>{result.trades.map((trade,index)=><tr key={index} className="border-t"><td className="p-2">{trade.symbol}</td><td>{trade.entry_day}</td><td>{trade.exit_day}</td><td>{trade.quantity}</td><td>{trade.pnl_cash.toFixed(2)}</td><td>{trade.exit_reason}</td></tr>)}</tbody></table></div>)}{report.excluded.map((row,index)=><p key={index} className="text-xs">{row.symbol}：{row.reason}</p>)}</div></details></>}
  </div>;
}
